---
title: "2_Explore_one_variable"
output: html_document
---

``` {r}
getwd()
#change directory
setwd("/Users/Souvik Banerjee/Desktop/Data_Science/Data_Analyst_Nanodegree/3_EDA/2_Explore_one_variable")

#To see files
list.files()

# Read data
pf<- read.csv('pseudo_facebook.tsv', sep="\t")

names(pf)
```
## Create Histogram of Users Birthdays
``` {r}
# Import ggplot2
library(ggplot2)

#plot histogram
qplot(x=dob_day, data=pf) +
  scale_x_continuous(breaks = 1:31)

```
## Faceting
``` {r}
qplot(x = dob_day, data = pf) +
  scale_x_continuous(breaks = 1:31) +
  facet_wrap(~dob_month, ncol=4)

```
## Friend Count
``` {r}
qplot(x = friend_count, data = pf, xlim = c(0,1000))

# Different way to do the same plot
qplot( x = friend_count, data = pf) +
  scale_x_continuous(limits = c(0,1000))
```
## Adjusting the bin width
``` {r}
qplot(x = friend_count, data=pf, binwidth = 25) +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0,1000, 50)) +
  facet_wrap(~gender)
```
## ommiting NA gender data
``` {r}
qplot(x = friend_count, data = subset(pf, !is.na(gender)), binwidth=25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0,1000,50)) +
  facet_wrap(~gender)
```
## Statistics by gender
``` {r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
```
## Tenure by months
``` {r}
qplot(x = tenure, data = pf, binwidth = 30,
      color = I('black'), fill=I('#099DD9'))
```
## Tenure by year
``` {r}
qplot(x = tenure/365, data = pf, binwidth = 0.25,
      color = I('black'), fill=I('#099DD9')) +
  scale_x_continuous(breaks=seq(1,7,1), limits=c(0,7))
```
## Labelling Plots
``` {r}
qplot( x = tenure/365, data = pf,  binwidth = 0.25,
       xlab = 'Number of years using Facebook',
       ylab = 'Number of users in sample',
       color = I('black'), fill=I('#099DD9')) +
  scale_x_continuous(breaks=seq(1,7,1), lim = c(0,7))
```

















